### ISSUE TITLE
Use a requirements.txt

### ISSUE THREAD

**Issue by anandbaburajan** [sr1j/ISS-Tracker#1]
This would help: https://note.nkmk.me/en/python-pip-install-requirements.

: )

**Comment by anandbaburajan** [comment]
Otherwise users might get errors like:

```
> python iss.py
Traceback (most recent call last):
  File "iss.py", line 4, in <module>
    import plotly.express as px
ModuleNotFoundError: No module named 'plotly'
```

**Comment by anandbaburajan** [comment]
Then mentioning the installation process in the readme would be helpful too.

**Comment by swsrkty** [comment]
Thank you for checking it out. I've fixed it : )

**Comment by anandbaburajan** [comment]
What about `PyQt5`?

**Comment by swsrkty** [comment]
Added it, thanks!
